export * from './actividades/Actividades';
export * from './auth/Login';
export * from './auth/Register';
export * from './autoevaluacion/Autoevaluacion';
export * from './autoevaluacion/InfoAutoevaluacion';
export * from './autoevaluacion/autoevaluacionDetalle';
export * from './calendario/Calendario';
export * from './common/Home';
export * from './denuncia/Denuncia';
export * from './denuncia/InfoDenuncia';
export * from './expertos/Expertos';
export * from './foro/Foro';
export * from './foro/DetallePost';
export * from './foro/crearPublicacion';
export * from './notificaciones/Notificaciones';
export * from './perfil/EditarPerfil';
export * from './perfil/PerfilUsuario';
export * from './admin/AdminDenuncia';
export * from './admin/AdminHome'
export * from './admin/AdminTestAutoevaluacion'
export * from './admin/AdminForo'
export * from './admin/AdminExpertos'
export * from './admin/AdminEventos'
export * from './admin/AdminActividades'
export * from './admin/AdminHome';
export * from './common/informacion';
